name : My first workflow
on: [push]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo "Hello, world! This is my first GitHub Actions workflow using branch main"
      - name: My second step
        run: pwd
      - name: My third step
        uses: actions/checkout@v4
      - name: My fourth step
        run: pwd
      - name: My fifth step
        run: ls -la
    